# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_leader', models.IntegerField(default=0)),
                ('task_description', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(verbose_name='Date Created')),
                ('modified_date', models.DateTimeField(verbose_name='Date Modified')),
            ],
        ),
    ]
